@port = 3000

##@host = http://localhost:{{port}}

@host = https://lifepath-back.onrender.com



GET {{host}}/api/fullName

###
GET {{host}}/api/personal

###
GET {{host}}/api/lastTraining/ca

###
GET {{host}}/api/trainings/en

###
GET {{host}}/api/experiences/ca

###
GET {{host}}/api/competences/en

###
GET {{host}}/api/projects/en
